/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_8bit(clk, rst, en, load_val, load, count);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire [7:0] _079_;
  wire [7:0] _080_;
  wire [31:0] _081_;
  wire [31:0] _082_;
  wire [31:0] _083_;
  wire _084_;
  wire _085_;
  input clk;
  wire clk;
  output [7:0] count;
  wire [7:0] count;
  input en;
  wire en;
  input load;
  wire load;
  input [7:0] load_val;
  wire [7:0] load_val;
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _086_ (
    .A(_011_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _087_ (
    .A(_016_),
    .B(_017_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _088_ (
    .A(_016_),
    .SLEEP(_017_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nand2b_1 _089_ (
    .A_N(_017_),
    .B(_016_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _090_ (
    .A(_008_),
    .B(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a221oi_1 _091_ (
    .A1(_017_),
    .A2(_018_),
    .B1(_027_),
    .B2(_008_),
    .C1(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _092_ (
    .A(_061_),
    .B(_031_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _093_ (
    .A(_017_),
    .B(_019_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(_009_),
    .B(_008_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a22o_1 _095_ (
    .A1(_009_),
    .A2(_027_),
    .B1(_028_),
    .B2(_033_),
    .X(_034_)
  );
  sky130_fd_sc_hd__o21ai_0 _096_ (
    .A1(_009_),
    .A2(_008_),
    .B1(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a21oi_1 _097_ (
    .A1(_032_),
    .A2(_035_),
    .B1(_061_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a21oi_1 _098_ (
    .A1(_009_),
    .A2(_008_),
    .B1(_010_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand3_1 _099_ (
    .A(_010_),
    .B(_009_),
    .C(_008_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a22oi_1 _100_ (
    .A1(_010_),
    .A2(_027_),
    .B1(_028_),
    .B2(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _101_ (
    .A(_036_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a21oi_1 _102_ (
    .A1(_017_),
    .A2(_020_),
    .B1(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(_061_),
    .B(_040_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and4_1 _104_ (
    .A(_011_),
    .B(_010_),
    .C(_009_),
    .D(_008_),
    .X(_041_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _105_ (
    .A1_N(_029_),
    .A2_N(_041_),
    .B1(_011_),
    .B2(_027_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a21oi_1 _106_ (
    .A1(_026_),
    .A2(_037_),
    .B1(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a21oi_1 _107_ (
    .A1(_017_),
    .A2(_021_),
    .B1(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _108_ (
    .A(_061_),
    .B(_044_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _109_ (
    .A(_017_),
    .B(_022_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _110_ (
    .A(_012_),
    .B(_027_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__and2_0 _111_ (
    .A(_012_),
    .B(_041_),
    .X(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _112_ (
    .A1(_029_),
    .A2(_047_),
    .B1(_046_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__o21ai_0 _113_ (
    .A1(_012_),
    .A2(_041_),
    .B1(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _114_ (
    .A1(_045_),
    .A2(_049_),
    .B1(_061_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _115_ (
    .A(_017_),
    .B(_023_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__and2_0 _116_ (
    .A(_013_),
    .B(_027_),
    .X(_051_)
  );
  sky130_fd_sc_hd__and3_1 _117_ (
    .A(_013_),
    .B(_012_),
    .C(_041_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _118_ (
    .A(_029_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__o22ai_1 _119_ (
    .A1(_013_),
    .A2(_047_),
    .B1(_051_),
    .B2(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a21oi_1 _120_ (
    .A1(_050_),
    .A2(_054_),
    .B1(_061_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(_017_),
    .B(_024_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand4_1 _122_ (
    .A(_014_),
    .B(_013_),
    .C(_012_),
    .D(_041_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a22o_1 _123_ (
    .A1(_014_),
    .A2(_027_),
    .B1(_028_),
    .B2(_056_),
    .X(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _124_ (
    .A1(_014_),
    .A2(_052_),
    .B1(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a21oi_1 _125_ (
    .A1(_055_),
    .A2(_058_),
    .B1(_061_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xnor2_1 _126_ (
    .A(_015_),
    .B(_056_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a222oi_1 _127_ (
    .A1(_017_),
    .A2(_025_),
    .B1(_028_),
    .B2(_059_),
    .C1(_027_),
    .C2(_015_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _128_ (
    .A(_061_),
    .B(_060_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__dfxtp_1 _129_ (
    .CLK(clk),
    .D(_064_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _130_ (
    .CLK(clk),
    .D(_066_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _131_ (
    .CLK(clk),
    .D(_068_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _132_ (
    .CLK(clk),
    .D(_070_),
    .Q(count[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _133_ (
    .CLK(clk),
    .D(_072_),
    .Q(count[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _134_ (
    .CLK(clk),
    .D(_074_),
    .Q(count[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _135_ (
    .CLK(clk),
    .D(_076_),
    .Q(count[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _136_ (
    .CLK(clk),
    .D(_078_),
    .Q(count[7])
  );
  assign { _081_[31:8], _081_[0] } = { 24'h000000, count[0] };
  assign _082_[31:1] = { 24'h000000, count[7:1] };
  assign { _083_[31:8], _083_[0] } = { 23'h000000, _081_[7], _082_[0] };
  assign _015_ = count[7];
  assign _014_ = count[6];
  assign _013_ = count[5];
  assign _012_ = count[4];
  assign _011_ = count[3];
  assign _010_ = count[2];
  assign _009_ = count[1];
  assign _008_ = count[0];
  assign _061_ = rst;
  assign _064_ = _000_;
  assign _066_ = _001_;
  assign _068_ = _002_;
  assign _070_ = _003_;
  assign _072_ = _004_;
  assign _074_ = _005_;
  assign _076_ = _006_;
  assign _078_ = _007_;
  assign _016_ = en;
  assign _017_ = load;
  assign _018_ = load_val[0];
  assign _019_ = load_val[1];
  assign _020_ = load_val[2];
  assign _021_ = load_val[3];
  assign _022_ = load_val[4];
  assign _023_ = load_val[5];
  assign _024_ = load_val[6];
  assign _025_ = load_val[7];
endmodule
