/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module shift_register(clk, rst, din, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  input clk;
  wire clk;
  input din;
  wire din;
  output [7:0] q;
  wire [7:0] q;
  input rst;
  wire rst;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _25_ (
    .A(_08_),
    .SLEEP(_16_),
    .X(_04_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _26_ (
    .A(_09_),
    .SLEEP(_16_),
    .X(_05_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _27_ (
    .A(_10_),
    .SLEEP(_16_),
    .X(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _28_ (
    .A(_11_),
    .SLEEP(_16_),
    .X(_07_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _29_ (
    .A(_12_),
    .SLEEP(_16_),
    .X(_00_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _30_ (
    .A(_13_),
    .SLEEP(_16_),
    .X(_01_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _31_ (
    .A(_14_),
    .SLEEP(_16_),
    .X(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _32_ (
    .A(_15_),
    .SLEEP(_16_),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(clk),
    .D(_21_),
    .Q(q[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(clk),
    .D(_22_),
    .Q(q[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _35_ (
    .CLK(clk),
    .D(_23_),
    .Q(q[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _36_ (
    .CLK(clk),
    .D(_24_),
    .Q(q[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _37_ (
    .CLK(clk),
    .D(_17_),
    .Q(q[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _38_ (
    .CLK(clk),
    .D(_18_),
    .Q(q[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _39_ (
    .CLK(clk),
    .D(_19_),
    .Q(q[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _40_ (
    .CLK(clk),
    .D(_20_),
    .Q(q[7])
  );
  assign _08_ = din;
  assign _16_ = rst;
  assign _21_ = _04_;
  assign _09_ = q[0];
  assign _22_ = _05_;
  assign _10_ = q[1];
  assign _23_ = _06_;
  assign _11_ = q[2];
  assign _24_ = _07_;
  assign _12_ = q[3];
  assign _17_ = _00_;
  assign _13_ = q[4];
  assign _18_ = _01_;
  assign _14_ = q[5];
  assign _19_ = _02_;
  assign _15_ = q[6];
  assign _20_ = _03_;
endmodule
