/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter(clk, rst, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [31:0] _17_;
  wire [31:0] _18_;
  wire [31:0] _19_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input rst;
  wire rst;
  sky130_fd_sc_hd__nor2_1 _20_ (
    .A(_12_),
    .B(_04_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(_04_),
    .B(_05_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _22_ (
    .A(_12_),
    .B(_08_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and3_1 _23_ (
    .A(_04_),
    .B(_05_),
    .C(_06_),
    .X(_09_)
  );
  sky130_fd_sc_hd__a21oi_1 _24_ (
    .A1(_04_),
    .A2(_05_),
    .B1(_06_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor3_1 _25_ (
    .A(_12_),
    .B(_09_),
    .C(_10_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _26_ (
    .A(_07_),
    .B(_09_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _27_ (
    .A(_12_),
    .B(_11_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__dfxtp_1 _28_ (
    .CLK(clk),
    .D(_13_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _29_ (
    .CLK(clk),
    .D(_14_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _30_ (
    .CLK(clk),
    .D(_15_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _31_ (
    .CLK(clk),
    .D(_16_),
    .Q(count[3])
  );
  assign { _17_[31:4], _17_[0] } = { 28'h0000000, count[0] };
  assign _18_[31:1] = { 28'h0000000, count[3:1] };
  assign { _19_[31:4], _19_[0] } = { 27'h0000000, _17_[3], _18_[0] };
  assign _12_ = rst;
  assign _13_ = _00_;
  assign _14_ = _01_;
  assign _15_ = _02_;
  assign _16_ = _03_;
  assign _04_ = count[0];
  assign _07_ = count[3];
  assign _05_ = count[1];
  assign _06_ = count[2];
endmodule
